CREATE TABLE "market_items" (
	"id" integer PRIMARY KEY NOT NULL,
	"name" varchar(255) NOT NULL,
	"rarity" varchar(50),
	"type" varchar(50),
	"level" integer,
	"buy_price" integer,
	"sell_price" integer,
	"buy_quantity" integer,
	"sell_quantity" integer,
	"chat_link" varchar(50),
	"img" text,
	"weapon_type" varchar(50),
	"stat_name" varchar(50),
	"first_added" timestamp,
	"last_update" timestamp,
	"1d_buy_price_avg" numeric(10, 2),
	"1d_sell_price_avg" numeric(10, 2),
	"1d_buy_quantity_avg" integer,
	"1d_sell_quantity_avg" integer,
	"1d_buy_value" integer,
	"1d_sell_value" integer,
	"1d_buy_sold" integer,
	"1d_sell_sold" integer,
	"1d_buy_listed" integer,
	"1d_sell_listed" integer,
	"1d_buy_delisted" integer,
	"1d_sell_delisted" integer,
	"1d_sell_delisted_value" integer
);
