ALTER TABLE "market_items" ALTER COLUMN "id" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "market_items" ALTER COLUMN "level" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "market_items" ALTER COLUMN "buy_price" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "market_items" ALTER COLUMN "sell_price" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "market_items" ALTER COLUMN "buy_quantity" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "market_items" ALTER COLUMN "sell_quantity" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "market_items" ALTER COLUMN "1d_buy_value" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "market_items" ALTER COLUMN "1d_sell_value" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "market_items" ALTER COLUMN "2d_buy_value" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "market_items" ALTER COLUMN "2d_sell_value" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "market_items" ALTER COLUMN "7d_buy_value" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "market_items" ALTER COLUMN "7d_sell_value" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "market_items" ALTER COLUMN "1m_buy_value" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "market_items" ALTER COLUMN "1m_sell_value" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "market_items" ALTER COLUMN "1d_buy_sold" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "market_items" ALTER COLUMN "1d_sell_sold" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "market_items" ALTER COLUMN "1d_buy_listed" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "market_items" ALTER COLUMN "1d_sell_listed" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "market_items" ALTER COLUMN "1d_buy_delisted" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "market_items" ALTER COLUMN "1d_sell_delisted" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "market_items" ALTER COLUMN "2d_buy_sold" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "market_items" ALTER COLUMN "2d_sell_sold" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "market_items" ALTER COLUMN "2d_buy_listed" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "market_items" ALTER COLUMN "2d_sell_listed" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "market_items" ALTER COLUMN "2d_buy_delisted" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "market_items" ALTER COLUMN "2d_sell_delisted" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "market_items" ALTER COLUMN "7d_buy_sold" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "market_items" ALTER COLUMN "7d_sell_sold" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "market_items" ALTER COLUMN "7d_buy_listed" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "market_items" ALTER COLUMN "7d_sell_listed" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "market_items" ALTER COLUMN "7d_buy_delisted" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "market_items" ALTER COLUMN "7d_sell_delisted" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "market_items" ALTER COLUMN "1m_buy_sold" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "market_items" ALTER COLUMN "1m_sell_sold" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "market_items" ALTER COLUMN "1m_buy_listed" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "market_items" ALTER COLUMN "1m_sell_listed" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "market_items" ALTER COLUMN "1m_buy_delisted" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "market_items" ALTER COLUMN "1m_sell_delisted" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "market_items" ALTER COLUMN "1d_sell_delisted_value" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "market_items" ALTER COLUMN "2d_sell_delisted_value" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "market_items" ALTER COLUMN "7d_sell_delisted_value" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "market_items" ALTER COLUMN "1m_sell_delisted_value" SET DATA TYPE bigint;